SuperDuperMarket/Controllers/BranchesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SuperDuperMarket.Models;

namespace SuperDuperMarket.Controllers
{
    [Authorize]
    public class BranchesController : BaseController
    {
        public BranchesController(SDMDbContext context) : base(context)
        {
        }

        [AllowAnonymous]
        public async Task<IActionResult> Index(string searchNameOrAddress)
        {
            IQueryable<Branch> branches = _context.Branches;


            // In case the user search by Branch Name 
            if (!String.IsNullOrEmpty(searchNameOrAddress))
            {
                branches = branches.Where(b => b.Name.Contains(searchNameOrAddress) || b.Address.Contains(searchNameOrAddress));
            }

            new GoogleMapsModel().ShowOnMap(branches.ToList(), ViewData);
            return View(branches);
        }

        // GET: Branches/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var branch = await _context.Branches
                .FirstOrDefaultAsync(m => m.Id == id);
            if (branch == null)
            {
                return NotFound();
            }
            new GoogleMapsModel().ShowOnMap(new List<Branch> { branch }, ViewData);

            return View(branch);
        }


        // GET: Branches/Create
        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Address,City,ZipCode")] Branch branch)
        {
            if (ModelState.IsValid)
            {
                _context.Add(branch);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(branch);
        }

        // GET: Branches/Edit/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var branch = await _context.Branches.FindAsync(id);
            if (branch == null)
            {
                return NotFound();
            }
            return View(branch);
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Address,City,ZipCode")] Branch branch)
        {
            if (id != branch.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(branch);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BranchExists(branch.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(branch);
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var branch = await _context.Branches
                .FirstOrDefaultAsync(m => m.Id == id);
            if (branch == null)
            {
                return NotFound();
            }

            return View(branch);
        }

        [HttpPost, ActionName("Delete")]
        [Authorize(Roles = "Admin")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var branch = await _context.Branches.FindAsync(id);
            _context.Branches.Remove(branch);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BranchExists(int id)
        {
            return _context.Branches.Any(e => e.Id == id);
        }
    }
}

SuperDuperMarket/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using SuperDuperMarket.Models;
using Microsoft.AspNetCore.Http;
using System.Security.Claims;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.EntityFrameworkCore;

namespace SuperDuperMarket.Controllers
{
    public class LoginController : BaseController
    {
        public LoginController(SDMDbContext context) : base(context)
        {
        }

        [AllowAnonymous]
        public ActionResult Register()
        {
            return View();
        }

        [HttpPost]
        [AllowAnonymous]
        public async Task<ActionResult> Register(string Email, string Password, string FirstName, string LastName,
            DateTime BirthDate, string Address, string City, int ZipCode)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Customers.Add(new Customer
                    {
                        Email = Email,
                        Password = Password,
                        FirstName = FirstName,
                        LastName = LastName,
                        BirthDate = BirthDate,
                        Address = Address,
                        City = City,
                        ZipCode = ZipCode,
                        IsAdmin = false,
                    });
                    await _context.SaveChangesAsync();
                    ViewData["Message"] = "You have been successfully registered!";
                    return Redirect("/Login/");
                }
                catch(DbUpdateException ex)
                {
                    ViewData["Message"] = $"{Email} already exists";
                }
            }
            return View();
        }
        [Authorize]
        public async Task<IActionResult> Details(int? id)
        {
            var userEmail = User.Claims.FirstOrDefault(x => x.Type == ClaimTypes.Email);
            Customer currentCustomer = _context.Customers.FirstOrDefault(x => x.Email == userEmail.Value);
            if (id == null)
            {
                return View(currentCustomer);
            }
            if (!User.HasClaim(ClaimTypes.Role, "Admin"))
            {
                if (currentCustomer.Id == id)
                {
                    return View(currentCustomer);
                }
                else
                {
                    return Redirect("/error/denied");
                }
            }
            else
            {    
                Customer customer = await _context.Customers.FirstOrDefaultAsync(m => m.Id == id);
                if (customer == null)
                {
                    //ViewData["Object"] = "Customer";
                    return NotFound();
                }
                return View(customer);
            }
        }

        [AllowAnonymous]
        public ActionResult Index()
        {
            // Put the ReturnUrl in the user's cookies
            if (Request.Query.ContainsKey("ReturnUrl"))
            {
                ViewBag.Message = "This is an authorized path, please login";
                Response.Cookies.Append("ReturnUrl", Request.Query["ReturnUrl"]);
            }
            return View();
        }

        [Authorize]
        public ActionResult Logout()
        {
            // Sign the user out
            HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            ClearCookies(Request, Response);
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult Index(string email, string password)
        {
            var user = _context.Customers.SingleOrDefault(customer => customer.Email == email && customer.Password == password);
            if (user == null)
            {
                ViewBag.Message = "Invalid username or password";
                return View();
            }

            // Create the user claims
            List<Claim> claims = new List<Claim>();
            if (user.IsAdmin)
            {
                // Set admin claims
                claims.Add(new Claim(ClaimTypes.Role, "Admin"));
                claims.Add(new Claim(ClaimTypes.Name, "Admin"));
            }
            else
            {
                // Set user claims
                claims.Add(new Claim(ClaimTypes.Role, "Customer"));
                claims.Add(new Claim(ClaimTypes.Name, user.FirstName + " " + user.LastName));
            }
            // Set username claim
            claims.Add(new Claim(ClaimTypes.Sid, user.Id.ToString()));
            claims.Add(new Claim(ClaimTypes.Email, user.Email));

            // Create the identity of the user
            ClaimsIdentity identity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);
            ClaimsPrincipal principal = new ClaimsPrincipal(identity);

            // Sign the user in
            HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, principal);

            // Handle ReturnUrl
            string redirect = "/Home/";
            if (Request.Cookies.ContainsKey("ReturnUrl"))
            {
                redirect = Request.Cookies["ReturnUrl"];
                Response.Cookies.Delete("ReturnUrl");
            }
            ClearCookies(Request, Response);

            return Redirect(redirect);
        }

        [Authorize(Roles = "Admin")]
        public ActionResult List()
        {
            return View(_context.Customers.ToList());
        }


        // GET: Products/Delete/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var customer = await _context.Customers
                .FirstOrDefaultAsync(m => m.Id == id);
            if (customer == null)
            {
                return NotFound();
            }

            if (customer.IsAdmin) return RedirectToAction(nameof(List));

            return View(customer);
        }


        // POST: Products/Delete/5
        [Authorize(Roles = "Admin")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var customer = await _context.Customers.FindAsync(id);
            _context.Customers.Remove(customer);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(List));
        }


        [Authorize]
        // GET: Customers/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            int userId = int.Parse(User.Claims.FirstOrDefault(c => c.Type == ClaimTypes.Sid).Value);
            int customerId = -1;
            if (id == null)
            {
                customerId = userId;
            }
            else
            {
                if (id == userId || User.IsInRole("Admin"))
                    customerId = (int)id;
                else
                    return Redirect("/error/denied");
            }

            var customer = await _context.Customers.FindAsync(customerId);
            if (customer == null)
            {
                return NotFound();
            }
            return View(customer);
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Email,FirstName,LastName,BirthDate,Password,Address,City,ZipCode")] Customer customer)
        {
            int userId = int.Parse(User.Claims.FirstOrDefault(c => c.Type == ClaimTypes.Sid).Value);
            if (id != customer.Id)
            {
                return NotFound();
            }
            if (userId != id && !User.IsInRole("Admin"))
            {
                return Redirect("/error/denied");
            }

            if (ModelState.IsValid)
            {
                try
                {
                    Customer currentCustomer = _context.Customers.AsNoTracking().FirstOrDefault(c => c.Id == id);
                    customer.IsAdmin = currentCustomer.IsAdmin;
                    _context.Update(customer);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CustomerExists(customer.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                if (User.IsInRole("Admin"))
                    return RedirectToAction(nameof(List));
                return RedirectToAction(nameof(Details));
            }
            return View(customer);
        }


        private bool CustomerExists(int id)
        {
            return _context.Customers.Any(e => e.Id == id);
        }
    }
}


SuperDuperMarket/Views/Shared/_Layout.cshtml
﻿@using Microsoft.AspNetCore.Http
@using System.Security.Claims
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title> @ViewData["Title"] - SuperDuperMarket</title>

        <link rel="stylesheet" href="~/lib/chartjs/dist/Chart.min.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        <link rel="stylesheet" href="~/css/googlemaps.css" />
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/journal.bootwatch.css" />


        <script src="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>
        <script src="~/lib/jscookie/dist/js.cookie.js"></script>
        <script src="/lib/chartjs/dist/Chart.min.js"></script>
        <script src="~/lib/d3/d3.min.js"></script>
        <script src="~/lib/dimple/dimple.v2.3.0.min.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        <script src="~/js/googlemaps.js" asp-append-version="true"></script>
        <script src="~/js/cookies.js" asp-append-version="true"></script>
    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Super Duper Market </a>
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                        <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                        <li><a asp-area="" asp-controller="Branches" asp-action="">Branches</a></li>
                        <li><a asp-area="" asp-controller="Products" asp-action="">Products</a></li>
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li> @Html.ActionLink("My Cart","Index","AddToCart", null, new { id= "btnCart" }) </li> 
                             @if (User.Identity.IsAuthenticated && User.HasClaim(ClaimTypes.Role, "Admin"))
                            {
                                <li> @Html.ActionLink("Orders","Index","Orders")</li>
                                <li><a asp-area="" asp-controller="Statistics" asp-action="">Statistics</a></li>
                                <li><a asp-area="" asp-controller="Login" asp-action="List">Customers</a></li>
                            } else{
                            <li> @Html.ActionLink("Orders", "Index", "Orders", new { id = User.Claims
                            .Where(c => c.Type == ClaimTypes.Sid).Select(c => c.Value).SingleOrDefault() })</li>
                            }
                        }
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        @if (User.Identity.IsAuthenticated)
                        {
                            if (User.HasClaim(ClaimTypes.Role, "Admin"))
                            {
                                <li><a href="/login/details">Welcome, Admin</a></li>
                                <li class="logout">@Html.ActionLink("Logout", "Logout", "Login")</li>
                            }
                            else
                            {
                                <li><a href="/login/details">Welcome, @User.Identity.Name </a></li>
                                <li class="logout">@Html.ActionLink("Logout", "Logout", "Login")</li>
                            }
                        }
                        else
                        {
                            <li><a>Welcome, Guest </a></li>
                            <li>@Html.ActionLink("Login", "Index", "Login")</li>
                            <li>@Html.ActionLink("Register", "Register", "Login")</li>
                        }
                    </ul>
                </div>
            </div>
        </nav>

        <partial name="_CookieConsentPartial" />

        <div class="container body-content">
            @RenderBody()
            <hr />
            <footer>
                <p>&copy; 2019 - SuperDuperMarket</p>
            </footer>
        </div>

        @RenderSection("Scripts", required: false)
    </body>
</html>