SuperDuperMarket/Models/Order.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SuperDuperMarket.Models
{
    public class Order
    {

        [Key]
        public int Id { get; set; }

        public int CustomerId { get; set; }
        [ForeignKey("CustomerId")]
        public virtual Customer Customer { get; set; }
        public int BranchId { get; set; }
        [ForeignKey("BranchId")]
        public virtual Branch Branch { get; set; }

        public DateTime CreationDate { get; set; }
        public ICollection<OrderProducts> OrderProduct { get; set; }
    }

}

SuperDuperMarket/Controllers/OrdersController.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Dynamic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SuperDuperMarket.Models;


// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace SuperDuperMarket.Controllers
{
    [Authorize]
    public class OrdersController : BaseController
    {
        public OrdersController(SDMDbContext context) : base(context)
        {

        }


        [Authorize(Roles = "Admin, Customer")]
        public IActionResult Index(int? id, string searchString,
             double searchMinPrice = 0, double searchMaxPrice = 9999999,
             double searchMinQuantity = 0, double searchMaxQuantity = 9999999)
        {
             if (searchMaxQuantity == 0) searchMaxQuantity = double.MaxValue;
            if (searchMaxPrice == 0) searchMaxPrice = double.MaxValue;
            int sid = int.Parse(User.Claims
                            .Where(c => c.Type == ClaimTypes.Sid)
                            .Select(c => c.Value).SingleOrDefault());
            // Checking if other user want to see orders that are not his
            if (((id == null) && (!User.IsInRole("Admin")))
                || ((id != sid) && (!User.IsInRole("Admin"))))
            {
                return Redirect("/error/denied");
            }


            IQueryable<Order> orders = _context.Orders.Include(o => o.OrderProduct).ThenInclude(orp => orp.Product);
            if (!String.IsNullOrEmpty(searchString))
                orders = orders.Where(s => s.Branch.Name.Contains(searchString));
            if (id != null)
                orders = orders.Where(o => o.CustomerId == id);
            orders = orders.Where(order =>
                isBetween(searchMinPrice, searchMaxPrice, order.OrderProduct.Sum(orp => orp.Product.Price * orp.Quantity))
                && isBetween(searchMinQuantity, searchMaxQuantity, order.OrderProduct.Sum(orp => orp.Quantity)));
            var query = orders.Join(_context.OrderProducts,
                o => o.Id,
                (op) => op.OrderId,
                 (o, op) =>
                 new
                 {
                     OrdererName = o.Customer.FirstName + " " + o.Customer.LastName,
                     Branch = o.Branch.Name,
                     OrderID = o.Id,
                     OrderProd = op,
                     Time = o.CreationDate
                 });

            var groupBy = query.GroupBy(o => o.OrderID);
            var data = new List<Tuple<String, int, List<Dictionary<String, String>>, string, double, DateTime>>();
            foreach (var group in groupBy)
            {
                var order = group.First();
                
                var products = group.Select(p => p).Join(_context.Products,
                     op => op.OrderProd.ProductId,
                      p => p.Id,
                      (op, p) =>
                      new Dictionary<String, String>
                      {
                          { "Quantity",op.OrderProd.Quantity.ToString()},
                          { "Image" , p.ImagePath },
                          { "Name" , p.Name },
                          { "Price" , p.Price.ToString()}
                      }).ToList();

                double totalPrice = 0;
                int totalQuantity = 0;
                foreach (var product in products)
                {
                    totalPrice += double.Parse(product["Price"]) * int.Parse(product["Quantity"]);
                }
                                
                    data.Add(Tuple.Create(order.OrdererName, order.OrderID, products, order.Branch, totalPrice, order.Time));
            }
            
            return View(data);
        }

        public static bool isBetween (double min, double max, double val)
        {
            return (val <= max && val >= min);
        }
    }
}

SuperDuperMarket/Views/Orders/Index.cshtml
@model List<Tuple<String, int, List <Dictionary<String, String>>, string, Double, DateTime>>
<br />
<div>
    <div class="row">
        <div class="col-md-6">
            <h1>Orders</h1>
        </div>
        <div class="col-md-6">
            
        </div>
    </div>
</div>
<div>
    @if (Model.Count == 0)
    {
        <h4>No orders to show</h4>
        <a asp-controller="Orders">Show all Orders </a>
    }
    else
    { 
        <hr />
        <div class="row">
            <div class="col-md-3">
                <form asp-controller="Orders" asp-action="Index">
                    <div class="thumbnail">
                        <h4>Filter</h4>
                        <div class="input-group input-group-sm">
                            <label class="input-group-addon">Branch:</label>
                            <input type="text" class="form-control" name="SearchString">
                        </div>
                        <div class="input-group input-group-sm">
                            <label class="input-group-addon">Price:</label>
                            <input type="number" class="form-control" min="0" step="0.1" value="0" name="searchMinPrice">
                            <label class="input-group-addon">-></label>
                            <input type="number" class="form-control" min="0" step="0.1" value="0" name="searchMaxPrice">
                        </div>
                        <div class="input-group input-group-sm">
                            <label class="input-group-addon">Quantity:</label>
                            <input type="number" class="form-control" min="0" value="0" name="searchMinQuantity">
                            <label class="input-group-addon">-></label>
                            <input type="number" class="form-control" min="0" value="0" name="searchMaxQuantity">
                        </div>

                        <input type="submit" class="btn btn-primary form-control" style="height: 300%;" value="Filter" />
                    </div>
                </form>
            </div>
            <div class="col-md-9">
                @foreach (var item in Model)
                {
                    <div class="row">
                        <div class="col-md-12">
                            <div class="thumbnail">
                                <h3>Order# @item.Item2</h3>
                                <hr />
                                <dl class="dl-horizontal">
                                    <dt>Made by</dt>
                                    <dd>@item.Item1</dd>
                                    <dt>Branch </dt>
                                    <dd>@item.Item4</dd>
                                    <dt>Time</dt>
                                    <dd>@item.Item6</dd>
                                    <dt>Price </dt>
                                    <dd>@item.Item5₪</dd>
                                </dl>

                                <button class="btn btn-info form-control" type="button" data-toggle="collapse" data-target="#collapse@(item.Item2)" aria-expanded="false" aria-controls="collapse@(item.Item2)">Details</button>
                                <div class="collapse" id="collapse@(item.Item2)">
                                    <div class="card card-body ">
                                        <div class="table-wrapper-scroll-y my-custom-scrollbar">
                                            <table class="table">
                                                <tr>
                                                    <th>Product</th>
                                                    <th>Quantity</th>
                                                    <th>Price</th>
                                                </tr>
                                                @foreach (var innerItem in @item.Item3)
                                                {
                                                    <tr>
                                                        <td>
                                                            <img class="image-cart" src="@Url.Content(@innerItem.GetValueOrDefault("Image"))" />
                                                            @innerItem.GetValueOrDefault("Name")
                                                        </td>
                                                        <td>@innerItem.GetValueOrDefault("Quantity")</td>
                                                        <td>@innerItem.GetValueOrDefault("Price")₪ X @innerItem.GetValueOrDefault("Price") = @(double.Parse(innerItem.GetValueOrDefault("Price")) * int.Parse(innerItem.GetValueOrDefault("Quantity")))₪</td>
                                                    </tr>
                                                }
                                            </table>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
            }
</div>